name: 'Builds Solidity contracts and caches dependencies and artifacts'
inputs:
  node_version:
    description: 'Node.js version'
    default: '16'
runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
    - name: Restore dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
    - name: Compile Solidity contracts
      run: npm run compile
      shell: bash
    - name: Cache artifacts
      uses: actions/cache@v2
      with:
        path: |
           ./types
           ./artifacts
           ./cache
        key: artifacts-${{ github.sha }}
