name: CI

on:
  pull_request:
    types: [opened, synchronize] # Trigger workflow on PR creation and when a commit is pushed.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build contracts and cache artifacts
        uses: ./.github/actions/build-contracts

  unit-test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        suite: ['unit', 'scenario']
    steps:
      - uses: actions/checkout@v2
      - name: Restore contract artifacts from cache
        uses: ./.github/actions/restore-contracts
      - name: Run ${{ matrix.suite }} tests
        env:
          ALCHEMY_ACCESS_TOKEN: ${{ secrets.ALCHEMY_ACCESS_TOKEN }}
        run: npm run test:${{ matrix.suite }}

  integration-test:
    runs-on: ubuntu-latest
    needs: [unit-test]
    strategy:
      max-parallel: 3
      matrix:
        suite: ['integration:execute-strategy', 'integration:exit', 'integration:rewards']
    steps:
      - uses: actions/checkout@v2
      - name: Restore contract artifacts from cache
        uses: ./.github/actions/restore-contracts
      - name: Run ${{ matrix.suite }} tests
        env:
          ALCHEMY_ACCESS_TOKEN: ${{ secrets.ALCHEMY_ACCESS_TOKEN }}
        run: npm run test:${{ matrix.suite }}
